/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_foxleezh_ndk_cpp_NativeTest */

#ifndef _Included_com_foxleezh_ndk_cpp_NativeTest
#define _Included_com_foxleezh_ndk_cpp_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_foxleezh_ndk_cpp_NativeTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_foxleezh_ndk_cpp_NativeTest_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
